from __future__ import annotations

from binaryninja import SectionSemantics, SegmentFlag

from ...core.regions import RegionSpec


WII_REGIONS: list[RegionSpec] = [
    RegionSpec(
        name="OSGlobals",
        vaddr=0x80000000,
        length=0x3100,
        flags=SegmentFlag.SegmentReadable | SegmentFlag.SegmentWritable,
        section="OSGlobals",
        section_semantics=SectionSemantics.ReadWriteDataSectionSemantics,
        section_type="Data",
    ),
    RegionSpec(
        name="CP",
        vaddr=0xCC000000,
        length=0x80,
        flags=SegmentFlag.SegmentReadable | SegmentFlag.SegmentWritable,
        section="CP",
        section_semantics=SectionSemantics.ReadWriteDataSectionSemantics,
        section_type="MMIO",
    ),
    RegionSpec(
        name="PE",
        vaddr=0xCC001000,
        length=0x100,
        flags=SegmentFlag.SegmentReadable | SegmentFlag.SegmentWritable,
        section="PE",
        section_semantics=SectionSemantics.ReadWriteDataSectionSemantics,
        section_type="MMIO",
    ),
    RegionSpec(
        name="VI",
        vaddr=0xCC002000,
        length=0x100,
        flags=SegmentFlag.SegmentReadable | SegmentFlag.SegmentWritable,
        section="VI",
        section_semantics=SectionSemantics.ReadWriteDataSectionSemantics,
        section_type="MMIO",
    ),
    RegionSpec(
        name="PI",
        vaddr=0xCC003000,
        length=0x100,
        flags=SegmentFlag.SegmentReadable | SegmentFlag.SegmentWritable,
        section="PI",
        section_semantics=SectionSemantics.ReadWriteDataSectionSemantics,
        section_type="MMIO",
    ),
    RegionSpec(
        name="MI",
        vaddr=0xCC004000,
        length=0x80,
        flags=SegmentFlag.SegmentReadable | SegmentFlag.SegmentWritable,
        section="MI",
        section_semantics=SectionSemantics.ReadWriteDataSectionSemantics,
        section_type="MMIO",
    ),
    RegionSpec(
        name="DSP",
        vaddr=0xCC005000,
        length=0x200,
        flags=SegmentFlag.SegmentReadable | SegmentFlag.SegmentWritable,
        section="DSP",
        section_semantics=SectionSemantics.ReadWriteDataSectionSemantics,
        section_type="MMIO",
    ),
    RegionSpec(
        name="DI",
        vaddr=0xCC006000,
        length=0x40,
        flags=SegmentFlag.SegmentReadable | SegmentFlag.SegmentWritable,
        section="DI",
        section_semantics=SectionSemantics.ReadWriteDataSectionSemantics,
        section_type="MMIO",
    ),
    RegionSpec(
        name="SI",
        vaddr=0xCC006400,
        length=0x100,
        flags=SegmentFlag.SegmentReadable | SegmentFlag.SegmentWritable,
        section="SI",
        section_semantics=SectionSemantics.ReadWriteDataSectionSemantics,
        section_type="MMIO",
    ),
    RegionSpec(
        name="EXI",
        vaddr=0xCC006800,
        length=0x40,
        flags=SegmentFlag.SegmentReadable | SegmentFlag.SegmentWritable,
        section="EXI",
        section_semantics=SectionSemantics.ReadWriteDataSectionSemantics,
        section_type="MMIO",
    ),
    RegionSpec(
        name="AI",
        vaddr=0xCC006C00,
        length=0x40,
        flags=SegmentFlag.SegmentReadable | SegmentFlag.SegmentWritable,
        section="AI",
        section_semantics=SectionSemantics.ReadWriteDataSectionSemantics,
        section_type="MMIO",
    ),
    RegionSpec(
        name="GXFIFO",
        vaddr=0xCC008000,
        length=0x8,
        flags=SegmentFlag.SegmentReadable | SegmentFlag.SegmentWritable,
        section="GXFIFO",
        section_semantics=SectionSemantics.ReadWriteDataSectionSemantics,
        section_type="MMIO",
    ),
    RegionSpec(
        name="HOLLYWOOD_MMIO",
        vaddr=0xCD000000,
        length=0x4000,
        flags=SegmentFlag.SegmentReadable | SegmentFlag.SegmentWritable,
        section="HOLLYWOOD_MMIO",
        section_semantics=SectionSemantics.ReadWriteDataSectionSemantics,
        section_type="MMIO",
    ),
    RegionSpec(
        name="MEM2_MMIO",
        vaddr=0xCD0B4000,
        length=0x2000,
        flags=SegmentFlag.SegmentReadable | SegmentFlag.SegmentWritable,
        section="MEM2_MMIO",
        section_semantics=SectionSemantics.ReadWriteDataSectionSemantics,
        section_type="MMIO",
    ),
]
